Student.destroy_all

louis = Student.create(name: 'Louis', grade_level: 2)
adam = Student.create(name: 'Adam', grade_level: 1)
Hewan = Student.create(name: 'Hewan', grade_level: 3)
mary = Student.create(name: 'Mary', grade_level: 1)
james = Student.create(name: 'James', grade_level: 2)
martin = Student.create(name: 'Martin', grade_level: 2)
habby = Student.create(name: 'Habby', grade_level: 3)


Assignment.destroy_all

adventure = Assignment.create(student: mary, grade: 'A', name: 'Choose Your Own Adventure', subject: 'Javascript')
tunr = Assignment.create(student: mary, grade: 'A', name: 'Tunr Rails', subject: 'Rails')
rainbow = Assignment.create(student: mary, grade: 'A', name: 'Color Scheme Switcher', subject: 'Javascript')
work = Assignment.create(student: mary, grade: 'A', name: 'Prework', subject: 'WDI')
voldemort = Assignment.create(student: mary, grade: 'A', name: 'Hogwarts', subject: 'WDI')
benjamins = Assignment.create(student: mary, grade: 'A', name: 'ATM', subject: 'Javascript')
adventure = Assignment.create(student: mary, grade: 'A', name: 'Choose Your Own Adventure', subject: 'Javascript')
tunr = Assignment.create(student: mary, grade: 'A', name: 'Tunr Rails', subject: 'Rails')
rainbow = Assignment.create(student: mary, grade: 'A', name: 'Color Scheme Switcher', subject: 'Javascript')
work = Assignment.create(student: mary, grade: 'A', name: 'Prework', subject: 'WDI')
voldemort = Assignment.create(student: mary, grade: 'A', name: 'Hogwarts', subject: 'WDI')
benjamins = Assignment.create(student: mary, grade: 'A', name: 'ATM', subject: 'Javascript')
adventure = Assignment.create(student: mary, grade: 'A', name: 'Choose Your Own Adventure', subject: 'Javascript')
tunr = Assignment.create(student: mary, grade: 'A', name: 'Tunr Rails', subject: 'Rails')
rainbow = Assignment.create(student: mary, grade: 'A', name: 'Color Scheme Switcher', subject: 'Javascript')
work = Assignment.create(student: mary, grade: 'A', name: 'Prework', subject: 'WDI')
voldemort = Assignment.create(student: mary, grade: 'A', name: 'Hogwarts', subject: 'WDI')
benjamins = Assignment.create(student: mary, grade: 'A', name: 'ATM', subject: 'Javascript')
adventure = Assignment.create(student: mary, grade: 'A', name: 'Choose Your Own Adventure', subject: 'Javascript')
tunr = Assignment.create(student: mary, grade: 'A', name: 'Tunr Rails', subject: 'Rails')
rainbow = Assignment.create(student: mary, grade: 'A', name: 'Color Scheme Switcher', subject: 'Javascript')
work = Assignment.create(student: mary, grade: 'A', name: 'Prework', subject: 'WDI')
voldemort = Assignment.create(student: mary, grade: 'A', name: 'Hogwarts', subject: 'WDI')
benjamins = Assignment.create(student: mary, grade: 'A', name: 'ATM', subject: 'Javascript')
adventure = Assignment.create(student: mary, grade: 'A', name: 'Choose Your Own Adventure', subject: 'Javascript')
tunr_rails = Assignment.create(student: mary, grade: 'A', name: 'Tunr Rails', subject: 'Rails')
rainbow = Assignment.create(student: mary, grade: 'A', name: 'Color Scheme Switcher', subject: 'Javascript')
work = Assignment.create(student: mary, grade: 'A', name: 'Prework', subject: 'WDI')
voldemort = Assignment.create(student: mary, grade: 'A', name: 'Hogwarts', subject: 'WDI')
benjamins = Assignment.create(student: mary, grade: 'A', name: 'ATM', subject: 'Javascript')
